In [1]:
import numpy as np
import pandas as pd

In [4]:
x1 = np.random.randint(-10,10,(2,3))
x1

array([[ 4, -4,  9],
       [-6,  2, -4]])

In [5]:
x2 = np.random.randint(-10,10,(2,3))
x2

array([[-4,  6,  7],
       [ 0,  5,  6]])

### Concatenate two arrays vertically

In [8]:
xfinal = np.concatenate([x1,x2])
xfinal

array([[ 4, -4,  9],
       [-6,  2, -4],
       [-4,  6,  7],
       [ 0,  5,  6]])

### Concatenate two arrays horizontally

In [10]:
xfinal2 = np.concatenate([x1,x2], axis=1)
xfinal2

array([[ 4, -4,  9, -4,  6,  7],
       [-6,  2, -4,  0,  5,  6]])

In [15]:
xfinal2.flatten()

array([ 4, -4,  9, -4,  6,  7, -6,  2, -4,  0,  5,  6])

In [16]:
xfinal2.shape

(2, 6)

In [20]:
df = pd.DataFrame(xfinal2.reshape(3,4), index=list('abc'), columns = [f'Col {i.upper()}' for i in 'abcd'])

In [21]:
df

Col A  Col B  Col C  Col D
a      4     -4      9     -4
b      6      7     -6      2
c     -4      0      5      6

In [81]:
indexes = [chr(i) for i in np.random.randint(65,75,len(s1))]
s1 = pd.Series(np.random.randint(-5,5,10), indexes).sort_index()
s1

A    1
C    0
C    2
E   -4
E    3
F   -3
F   -1
J    4
J   -4
J    2
dtype: int64

In [82]:
s2 = pd.Series(np.random.randint(-5,5,10), indexes).sort_index()
#indexes = [chr(i) for i in np.random.randint(76,91,len(s2))]
s2

A    2
C   -4
C    2
E    0
E   -4
F    0
F   -1
J   -3
J    3
J    0
dtype: int64

In [84]:
df = pd.concat([s1,s2], axis=1).sort_index()
df

0  1
A  1  2
C  0 -4
C  2  2
E -4  0
E  3 -4
F -3  0
F -1 -1
J  4 -3
J -4  3
J  2  0

In [115]:
from random import choice
indexes = [chr(i) for i in np.random.randint(65,91,10)]
s3 = pd.Series(np.random.randint(-5,5,10), indexes).sort_index()
# repeat some labels of series 3 from series 2
indexes2 = indexes[3:]
indexes2.extend([choice(indexes) for i in range(3)])
s4 = pd.Series(np.random.randint(-20,20,10), indexes2).sort_index()

In [116]:
s3

B   -1
D    2
H   -3
K    0
L    0
S   -2
U   -2
V    4
W    2
X    0
dtype: int64

In [117]:
s4

D   -15
H    -2
K    -4
L    11
S   -10
S     9
U     7
U    -2
V   -15
X     2
dtype: int64

In [120]:
df2 = pd.concat([s2,s3],axis=1)
df2

0    1
D -4.0  2.0
F  1.0  NaN
G  2.0  NaN
H  4.0 -3.0
I  2.0  NaN
K -2.0  0.0
M -2.0  NaN
N -1.0  NaN
T  1.0  NaN
U -5.0 -2.0
B  NaN -1.0
L  NaN  0.0
S  NaN -2.0
V  NaN  4.0
W  NaN  2.0
X  NaN  0.0

Los valores nan son debidos a que en esa fila, la etiqueta, y por lo tanto el valor asociado, no existía en la serie original. Si las series tenían etiquetas en común, el DataFrame resultante tiene valores para ambas columnas.

In [121]:
s2

D   -4
F    1
G    2
H    4
I    2
K   -2
M   -2
N   -1
T    1
U   -5
dtype: int64

Resetear el índice de una serie/df usando `reset_index`

In [122]:
s2.reset_index()

index  0
0     D -4
1     F  1
2     G  2
3     H  4
4     I  2
5     K -2
6     M -2
7     N -1
8     T  1
9     U -5

El índice aparece como una columna adicional por si queremos conservarlo. Si no es así, podemos usar la opción `drop=True` para que dicha columna no aparezca en el resultado final.

In [123]:
s2.reset_index(drop=True)

0   -4
1    1
2    2
3    4
4    2
5   -2
6   -2
7   -1
8    1
9   -5
dtype: int64

In [126]:
s1.head().sort_index()

A    1
C    0
C    2
E   -4
E    3
dtype: int64

In [127]:
s2.head().sort_index()

D   -4
F    1
G    2
H    4
I    2
dtype: int64

Los índices de s1 y s2 no coinciden. Al concatenar esas series, aparecerán valores `nan`. Para evitar esto, podemos resetear los índices de cada serie antes de concatenarlos

In [134]:
s1_noindex = s1.reset_index(drop=True)
s2_noindex = s2.reset_index(drop=True)
df = pd.concat([s1_noindex, s2_noindex], axis=1)
df.columns = ['Col 1', 'Col 2']
df

Col 1  Col 2
0      1     -4
1      0      1
2      2      2
3     -4      4
4      3      2
5     -3     -2
6     -1     -2
7      4     -1
8     -4      1
9      2     -5

`.append()` method is deprecated, so use `.concat()` insted